/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeScreens;

import Login.Login;
import admin.AdminPersonalDetails;
import admin.adminattendance;
import admin.adminexamprof;
import java.awt.Color;
import javax.swing.JPanel;
import admin.*;
import java.awt.Container;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MalindaRaneshDeshapr
 */
public class admin extends javax.swing.JFrame {
    String user;
    /**
     * Creates new form admin
     */
    public admin(String techerid) {
        this.setAlwaysOnTop(true);
        setExtendedState(MAXIMIZED_BOTH);
        //this.setLocationByPlatform(rootPaneCheckingEnabled);
        //this.setUndecorated(true);
        initComponents();
        this.user = techerid;
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        if(!user.equals("admin")){
            pnl_userAccounts.hide();
        }
        
        
    }

    private admin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        pnl_details = new javax.swing.JPanel();
        btn_details = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnl_attendance = new javax.swing.JPanel();
        btn_attendance = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnl_other = new javax.swing.JPanel();
        btn_other = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnl_leadership = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnl_performace = new javax.swing.JPanel();
        btn_performace = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_leadership1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnl_classdetails = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnl_userAccounts = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        deskpanal = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1, 2147483647));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));

        sidepane.setBackground(new java.awt.Color(0, 204, 153));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_details.setBackground(new java.awt.Color(0, 220, 153));
        pnl_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_detailsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_detailsMousePressed(evt);
            }
        });

        btn_details.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_details.setForeground(new java.awt.Color(255, 255, 255));
        btn_details.setText("Student Details");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student-with-graduation-cap (2).png"))); // NOI18N

        javax.swing.GroupLayout pnl_detailsLayout = new javax.swing.GroupLayout(pnl_details);
        pnl_details.setLayout(pnl_detailsLayout);
        pnl_detailsLayout.setHorizontalGroup(
            pnl_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detailsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_details, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnl_detailsLayout.setVerticalGroup(
            pnl_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_details)
                    .addComponent(jLabel3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(pnl_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 40));

        pnl_attendance.setBackground(new java.awt.Color(0, 204, 153));
        pnl_attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_attendanceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_attendanceMousePressed(evt);
            }
        });

        btn_attendance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_attendance.setForeground(new java.awt.Color(255, 255, 255));
        btn_attendance.setText("Attendance");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attendance.png"))); // NOI18N

        javax.swing.GroupLayout pnl_attendanceLayout = new javax.swing.GroupLayout(pnl_attendance);
        pnl_attendance.setLayout(pnl_attendanceLayout);
        pnl_attendanceLayout.setHorizontalGroup(
            pnl_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_attendanceLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_attendance)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnl_attendanceLayout.setVerticalGroup(
            pnl_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_attendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_attendance)
                    .addComponent(jLabel5))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(pnl_attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, -1));

        pnl_other.setBackground(new java.awt.Color(0, 204, 153));
        pnl_other.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_otherMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_otherMousePressed(evt);
            }
        });

        btn_other.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_other.setForeground(new java.awt.Color(255, 255, 255));
        btn_other.setText("Other Performance");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/otherp.png"))); // NOI18N

        javax.swing.GroupLayout pnl_otherLayout = new javax.swing.GroupLayout(pnl_other);
        pnl_other.setLayout(pnl_otherLayout);
        pnl_otherLayout.setHorizontalGroup(
            pnl_otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_otherLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_other)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnl_otherLayout.setVerticalGroup(
            pnl_otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_otherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_other)
                    .addComponent(jLabel9))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(pnl_other, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        pnl_leadership.setBackground(new java.awt.Color(0, 204, 153));
        pnl_leadership.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_leadershipMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_leadershipMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Leadership");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leadership.png"))); // NOI18N

        javax.swing.GroupLayout pnl_leadershipLayout = new javax.swing.GroupLayout(pnl_leadership);
        pnl_leadership.setLayout(pnl_leadershipLayout);
        pnl_leadershipLayout.setHorizontalGroup(
            pnl_leadershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_leadershipLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnl_leadershipLayout.setVerticalGroup(
            pnl_leadershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_leadershipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_leadershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(pnl_leadership, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, -1));

        pnl_performace.setBackground(new java.awt.Color(0, 204, 153));
        pnl_performace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_performaceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_performaceMousePressed(evt);
            }
        });

        btn_performace.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_performace.setForeground(new java.awt.Color(255, 255, 255));
        btn_performace.setText("Exam Performance");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam.png"))); // NOI18N

        javax.swing.GroupLayout pnl_performaceLayout = new javax.swing.GroupLayout(pnl_performace);
        pnl_performace.setLayout(pnl_performaceLayout);
        pnl_performaceLayout.setHorizontalGroup(
            pnl_performaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_performaceLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_performace)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnl_performaceLayout.setVerticalGroup(
            pnl_performaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_performaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_performaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_performace)
                    .addComponent(jLabel13))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(pnl_performace, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Management System");
        sidepane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 30));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 20));

        pnl_leadership1.setBackground(new java.awt.Color(0, 204, 153));
        pnl_leadership1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_leadership1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_leadership1MousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Teacher Details");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leadership.png"))); // NOI18N

        javax.swing.GroupLayout pnl_leadership1Layout = new javax.swing.GroupLayout(pnl_leadership1);
        pnl_leadership1.setLayout(pnl_leadership1Layout);
        pnl_leadership1Layout.setHorizontalGroup(
            pnl_leadership1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_leadership1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnl_leadership1Layout.setVerticalGroup(
            pnl_leadership1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_leadership1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_leadership1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(pnl_leadership1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, -1));

        pnl_classdetails.setBackground(new java.awt.Color(0, 204, 153));
        pnl_classdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_classdetailsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_classdetailsMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Class Details");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leadership.png"))); // NOI18N

        javax.swing.GroupLayout pnl_classdetailsLayout = new javax.swing.GroupLayout(pnl_classdetails);
        pnl_classdetails.setLayout(pnl_classdetailsLayout);
        pnl_classdetailsLayout.setHorizontalGroup(
            pnl_classdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_classdetailsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pnl_classdetailsLayout.setVerticalGroup(
            pnl_classdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_classdetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_classdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(pnl_classdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        pnl_userAccounts.setBackground(new java.awt.Color(0, 204, 153));
        pnl_userAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_userAccountsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_userAccountsMousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("User Accounts");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leadership.png"))); // NOI18N

        javax.swing.GroupLayout pnl_userAccountsLayout = new javax.swing.GroupLayout(pnl_userAccounts);
        pnl_userAccounts.setLayout(pnl_userAccountsLayout);
        pnl_userAccountsLayout.setHorizontalGroup(
            pnl_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userAccountsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnl_userAccountsLayout.setVerticalGroup(
            pnl_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_userAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(pnl_userAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (3).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 60, 60));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("WELCOME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("USER");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1016, 41, -1, -1));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        deskpanal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout deskpanalLayout = new javax.swing.GroupLayout(deskpanal);
        deskpanal.setLayout(deskpanalLayout);
        deskpanalLayout.setHorizontalGroup(
            deskpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1137, Short.MAX_VALUE)
        );
        deskpanalLayout.setVerticalGroup(
            deskpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(deskpanal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(deskpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(deskpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimise-button.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 20, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 20, 30));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 32000, Short.MAX_VALUE))
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        Login l1 = new Login();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
       this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void pnl_detailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_detailsMousePressed
        setColour(pnl_details);
        resetColour(pnl_attendance);
        resetColour(pnl_leadership);
        resetColour(pnl_performace);
        resetColour(pnl_other);
    }//GEN-LAST:event_pnl_detailsMousePressed

    private void pnl_attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_attendanceMouseClicked
        adminattendance n1;
        try {
            n1 = new adminattendance(user);
            deskpanal.removeAll();
        deskpanal.updateUI();
        deskpanal.add(n1).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_pnl_attendanceMouseClicked

    private void pnl_attendanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_attendanceMousePressed
        setColour(pnl_attendance);
        resetColour(pnl_details);
        resetColour(pnl_leadership);
        resetColour(pnl_performace);
        resetColour(pnl_other);
    }//GEN-LAST:event_pnl_attendanceMousePressed

    private void pnl_performaceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_performaceMousePressed
        setColour(pnl_performace);
        resetColour(pnl_attendance);
        resetColour(pnl_details);
        resetColour(pnl_leadership);
        resetColour(pnl_other);
    }//GEN-LAST:event_pnl_performaceMousePressed

    private void pnl_otherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_otherMousePressed
        setColour(pnl_other);
        resetColour(pnl_performace);
        resetColour(pnl_details);
        resetColour(pnl_attendance);
        resetColour(pnl_leadership);
    }//GEN-LAST:event_pnl_otherMousePressed

    private void pnl_leadershipMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_leadershipMousePressed
        setColour(pnl_leadership);
        resetColour(pnl_other);
        resetColour(pnl_details);
        resetColour(pnl_attendance);
        resetColour(pnl_performace);
        
    }//GEN-LAST:event_pnl_leadershipMousePressed

    private void pnl_leadership1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_leadership1MousePressed
        setColour(pnl_leadership);
        resetColour(pnl_other);
        resetColour(pnl_details);
        resetColour(pnl_attendance);
        resetColour(pnl_performace);
    }//GEN-LAST:event_pnl_leadership1MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        
    }//GEN-LAST:event_jLabel12MousePressed

    private void pnl_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_detailsMouseClicked
        AdminPersonalDetails n1  = new AdminPersonalDetails(user);
        deskpanal.removeAll();
        deskpanal.updateUI();
        deskpanal.add(n1).setVisible(true);
        
        n1.setFrameIcon(null);
        
    }//GEN-LAST:event_pnl_detailsMouseClicked

    private void pnl_performaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_performaceMouseClicked
        adminexamprof n1;
        try {
            n1 = new adminexamprof(user);
            deskpanal.removeAll();
        deskpanal.updateUI();
        deskpanal.add(n1).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
        
    }//GEN-LAST:event_pnl_performaceMouseClicked

    private void pnl_otherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_otherMouseClicked
        adminotherprof n1  = new adminotherprof();
        deskpanal.removeAll();
        deskpanal.updateUI();
        deskpanal.add(n1).setVisible(true);
    }//GEN-LAST:event_pnl_otherMouseClicked

    private void pnl_leadershipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_leadershipMouseClicked
        adminleadership n1  = new adminleadership();
        deskpanal.removeAll();
        deskpanal.updateUI();
        deskpanal.add(n1).setVisible(true);
    }//GEN-LAST:event_pnl_leadershipMouseClicked

    private void pnl_leadership1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_leadership1MouseClicked
       adminteacherdetails n1  = new adminteacherdetails();
        deskpanal.removeAll();
        deskpanal.updateUI();
        deskpanal.add(n1).setVisible(true);
    }//GEN-LAST:event_pnl_leadership1MouseClicked

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MousePressed

    private void pnl_classdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_classdetailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_classdetailsMouseClicked

    private void pnl_classdetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_classdetailsMousePressed
        setColour(pnl_classdetails);
        resetColour(pnl_other);
        resetColour(pnl_details);
        resetColour(pnl_attendance);
        resetColour(pnl_performace);
        
        adminclassdetails n1;
        try {
            n1 = new adminclassdetails();
            deskpanal.removeAll();
        deskpanal.updateUI();
        deskpanal.add(n1).setVisible(true);
        } catch (SQLException ex) {
            System.out.println("Malinda");
            //1Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_pnl_classdetailsMousePressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MousePressed

    private void pnl_userAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_userAccountsMouseClicked
        setColour(pnl_classdetails);
        resetColour(pnl_other);
        resetColour(pnl_details);
        resetColour(pnl_attendance);
        resetColour(pnl_performace);
        
        adminUserAccounts usera;
        try {
            usera = new adminUserAccounts();
            deskpanal.removeAll();
            deskpanal.updateUI();
            deskpanal.add(usera).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_pnl_userAccountsMouseClicked

    private void pnl_userAccountsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_userAccountsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_userAccountsMousePressed

    void setColour(JPanel pane1){
        pane1.setBackground(new Color(0,220,153));
    }
    
    void resetColour(JPanel pane1){
        pane1.setBackground(new Color(0,204,153));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btn_attendance;
    private javax.swing.JLabel btn_details;
    private javax.swing.JLabel btn_other;
    private javax.swing.JLabel btn_performace;
    private javax.swing.JPanel deskpanal;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnl_attendance;
    private javax.swing.JPanel pnl_classdetails;
    private javax.swing.JPanel pnl_details;
    private javax.swing.JPanel pnl_leadership;
    private javax.swing.JPanel pnl_leadership1;
    private javax.swing.JPanel pnl_other;
    private javax.swing.JPanel pnl_performace;
    private javax.swing.JPanel pnl_userAccounts;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
