/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 * This is file approve
 *
 * @author Osith
 */
public class adminfile extends javax.swing.JInternalFrame {

    public adminfile() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tab_studentRecord = new javax.swing.JTabbedPane();
        view = new javax.swing.JPanel();

        setBackground(new java.awt.Color(206, 255, 179));
        setBorder(null);
        setToolTipText("");
        setDoubleBuffered(true);
        setEnabled(false);
        setFocusCycleRoot(false);
        setOpaque(true);

        tab_studentRecord.setBackground(new java.awt.Color(206, 255, 179));
        tab_studentRecord.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tab_studentRecord.setToolTipText("");
        tab_studentRecord.setDoubleBuffered(true);
        tab_studentRecord.setOpaque(true);

        view.setBackground(new java.awt.Color(206, 255, 179));

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        tab_studentRecord.addTab("File Status", view);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_studentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_studentRecord)
        );

        tab_studentRecord.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane tab_studentRecord;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
