/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import DatabaseConnection.DbConnect;
import java.awt.Toolkit;
import java.io.IOException;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

/**
 *
 * @author MalindaRaneshDeshapr
 */
public class AdminPersonalDetails extends javax.swing.JInternalFrame {

    ResultSet rs;
    Connection conn;
    PreparedStatement pst;
    studentpersonaldetails p1 = new studentpersonaldetails();

    int indexno;
    String fullname;
    String nwi;
    Date birthday;
    String address;

    String mothernamee;
    String motherocuu;
    String fathernamee;
    String fatherocuu;

    int mothermob;
    int fathermob;
    int homeno;
    
    String user;

    public AdminPersonalDetails(String user) {
        conn = DbConnect.ConnectDb();
        this.user = user;
        initComponents();
        setRootPaneCheckingEnabled(false);
        
        if(!user.equals("admin")){
            btn_update.setEnabled(false);
            jTabbedPane1.disable();
        
        
        }

        /*LocalDateTime time = LocalDateTime.now();
        String time1 = time.toString();*/
        Date date = new Date();
        Calendar calendar = new GregorianCalendar();
        calendar.setTime(date);
        int year = calendar.get(Calendar.YEAR);

        String sql1 = "SELECT  class_grade,class_subclass,class_year FROM classes WHERE class_year=? GROUP BY class_grade ";

        try {
            pst = conn.prepareStatement(sql1);
            pst.setInt(1, year);
            rs = pst.executeQuery();

            while (rs.next()) {
                combo_grade.addItem(rs.getString("class_grade"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

        //setFrameIcon(null);
        //setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        view = new javax.swing.JPanel();
        PDPanal1 = new javax.swing.JPanel();
        txt_address = new javax.swing.JTextField();
        txt_index = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_name_initial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_siblings = new javax.swing.JTextArea();
        txt_full_name = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_birthday = new com.toedter.calendar.JDateChooser();
        ParentDPanal1 = new javax.swing.JPanel();
        txt_mother_name = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_mother_occupation = new javax.swing.JTextField();
        txt_father_name = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_father_occupation = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        CDPanal1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        txt_father_mobile = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_mother_mobile = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_home = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        RDPanal1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Class_reg = new javax.swing.JTextField();
        txt_regdate = new com.toedter.calendar.JDateChooser();
        jLabel40 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_students = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        insert = new javax.swing.JPanel();
        PDPanal = new javax.swing.JPanel();
        txt_add = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_sib = new javax.swing.JTextArea();
        txt_sib = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_fullname = new javax.swing.JTextField();
        txt_nameInitial = new javax.swing.JTextField();
        txt_datechooser = new com.toedter.calendar.JDateChooser();
        ParentDPanal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        mothername = new javax.swing.JTextField();
        motherocu = new javax.swing.JTextField();
        fathername = new javax.swing.JTextField();
        fatherocu = new javax.swing.JTextField();
        RDPanal = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        combo_grade = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        combo_subclass = new javax.swing.JComboBox<>();
        regdatechooser = new com.toedter.calendar.JDateChooser();
        CDPanal = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fathermobile = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        mothermobile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        homenum = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(206, 255, 179));
        setBorder(null);
        setToolTipText("");
        setDoubleBuffered(true);
        setEnabled(false);
        setFocusCycleRoot(false);
        setOpaque(true);

        jTabbedPane1.setBackground(new java.awt.Color(206, 255, 179));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setOpaque(true);

        view.setBackground(new java.awt.Color(206, 255, 179));

        PDPanal1.setBackground(new java.awt.Color(204, 204, 255));
        PDPanal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setText("Full Name :");

        jLabel22.setText("Birthday :");

        jLabel23.setText("Index No :");

        jLabel24.setText("Full Name with Initial :");

        txt_siblings.setColumns(20);
        txt_siblings.setRows(5);
        jScrollPane2.setViewportView(txt_siblings);

        jLabel26.setText("Siblings Details :");

        jLabel27.setText("Address :");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Personal Details");

        javax.swing.GroupLayout PDPanal1Layout = new javax.swing.GroupLayout(PDPanal1);
        PDPanal1.setLayout(PDPanal1Layout);
        PDPanal1Layout.setHorizontalGroup(
            PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDPanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addGroup(PDPanal1Layout.createSequentialGroup()
                        .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_index, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name_initial, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_birthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        PDPanal1Layout.setVerticalGroup(
            PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDPanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(16, 16, 16)
                .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDPanal1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txt_name_initial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDPanal1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(12, 12, 12)
                        .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(PDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ParentDPanal1.setBackground(new java.awt.Color(255, 204, 204));
        ParentDPanal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Mother's Name :");

        jLabel29.setText("Mother's Occupation :");

        jLabel30.setText("Father's Name :");

        jLabel31.setText("Father's Occupation :");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("Parents Details");

        javax.swing.GroupLayout ParentDPanal1Layout = new javax.swing.GroupLayout(ParentDPanal1);
        ParentDPanal1.setLayout(ParentDPanal1Layout);
        ParentDPanal1Layout.setHorizontalGroup(
            ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParentDPanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ParentDPanal1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mother_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel32)
                    .addGroup(ParentDPanal1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(31, 31, 31)
                        .addComponent(txt_mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ParentDPanal1Layout.createSequentialGroup()
                        .addGroup(ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_father_name, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_father_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ParentDPanal1Layout.setVerticalGroup(
            ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParentDPanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_mother_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_father_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParentDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_father_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        CDPanal1.setBackground(new java.awt.Color(204, 255, 204));
        CDPanal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setText("Father's Mobile :");

        jLabel34.setText("Mother's Mobile :");

        jLabel35.setText("Home :");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel36.setText("Contact Details");

        javax.swing.GroupLayout CDPanal1Layout = new javax.swing.GroupLayout(CDPanal1);
        CDPanal1.setLayout(CDPanal1Layout);
        CDPanal1Layout.setHorizontalGroup(
            CDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CDPanal1Layout.createSequentialGroup()
                .addGroup(CDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CDPanal1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_mother_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CDPanal1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_home, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CDPanal1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(CDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CDPanal1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel33)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txt_father_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );
        CDPanal1Layout.setVerticalGroup(
            CDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CDPanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(CDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txt_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txt_mother_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(CDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CDPanal1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(CDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(txt_father_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        RDPanal1.setBackground(new java.awt.Color(204, 204, 204));
        RDPanal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel37.setText("Date of Registration :");

        jLabel38.setText("Class of Regsitration :");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel39.setText("Registration Details");

        javax.swing.GroupLayout RDPanal1Layout = new javax.swing.GroupLayout(RDPanal1);
        RDPanal1.setLayout(RDPanal1Layout);
        RDPanal1Layout.setHorizontalGroup(
            RDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RDPanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel39)
                    .addGroup(RDPanal1Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Class_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RDPanal1Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_regdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        RDPanal1Layout.setVerticalGroup(
            RDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RDPanal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(txt_regdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(RDPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Class_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel40.setText("Search By :");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Index No");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Full Name");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Contact No");

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        tbl_students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_students);

        jButton4.setText("Export Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewLayout.createSequentialGroup()
                        .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PDPanal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(viewLayout.createSequentialGroup()
                                .addComponent(RDPanal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_update)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CDPanal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ParentDPanal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(viewLayout.createSequentialGroup()
                        .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewLayout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(viewLayout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(10, 10, 10)
                                        .addComponent(jRadioButton2)
                                        .addGap(10, 10, 10)
                                        .addComponent(jRadioButton3))
                                    .addComponent(txt_search)))
                            .addGroup(viewLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(btn_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)))
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewLayout.createSequentialGroup()
                        .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addGap(18, 18, 18)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_search)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewLayout.createSequentialGroup()
                        .addComponent(PDPanal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RDPanal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update))
                        .addGap(42, 42, 42))
                    .addGroup(viewLayout.createSequentialGroup()
                        .addComponent(ParentDPanal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CDPanal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("View Personal Details", view);

        insert.setBackground(new java.awt.Color(206, 255, 179));
        insert.setPreferredSize(new java.awt.Dimension(1500, 600));

        PDPanal.setBackground(new java.awt.Color(255, 255, 255));
        PDPanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Full Name :");

        jLabel4.setText("Birthday :");

        jLabel3.setText("Full Name with Initial :");

        jLabel14.setText("(Index No)");

        txtarea_sib.setColumns(20);
        txtarea_sib.setRows(5);
        jScrollPane1.setViewportView(txtarea_sib);

        jLabel13.setText("Siblings Details :");

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Address :");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Personal Details");

        javax.swing.GroupLayout PDPanalLayout = new javax.swing.GroupLayout(PDPanal);
        PDPanal.setLayout(PDPanalLayout);
        PDPanalLayout.setHorizontalGroup(
            PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addGroup(PDPanalLayout.createSequentialGroup()
                        .addGroup(PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_add, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addGroup(PDPanalLayout.createSequentialGroup()
                                .addComponent(txt_sib, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(24, 24, 24)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(txt_nameInitial, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(txt_datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        PDPanalLayout.setVerticalGroup(
            PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nameInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDPanalLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(PDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_sib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ParentDPanal.setBackground(new java.awt.Color(255, 255, 255));
        ParentDPanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Mother's Name :");

        jLabel7.setText("Mother's Occupation :");

        jLabel8.setText("Father's Name :");

        jLabel9.setText("Father's Occupation :");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Parents Details");

        javax.swing.GroupLayout ParentDPanalLayout = new javax.swing.GroupLayout(ParentDPanal);
        ParentDPanal.setLayout(ParentDPanalLayout);
        ParentDPanalLayout.setHorizontalGroup(
            ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParentDPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mothername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addGroup(ParentDPanalLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(fatherocu, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ParentDPanalLayout.createSequentialGroup()
                            .addGroup(ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(motherocu, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ParentDPanalLayout.setVerticalGroup(
            ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParentDPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mothername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(motherocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fathername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParentDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fatherocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        RDPanal.setBackground(new java.awt.Color(255, 255, 255));
        RDPanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Date of Registration :");

        combo_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_gradeActionPerformed(evt);
            }
        });

        jLabel12.setText("Class of Regsitration :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Registration Details");

        javax.swing.GroupLayout RDPanalLayout = new javax.swing.GroupLayout(RDPanal);
        RDPanal.setLayout(RDPanalLayout);
        RDPanalLayout.setHorizontalGroup(
            RDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RDPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(RDPanalLayout.createSequentialGroup()
                        .addGroup(RDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RDPanalLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(14, 14, 14)
                                .addComponent(regdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RDPanalLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_subclass, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RDPanalLayout.setVerticalGroup(
            RDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RDPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(regdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(RDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_subclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        CDPanal.setBackground(new java.awt.Color(255, 255, 255));
        CDPanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Father's Mobile :");

        fathermobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fathermobileKeyTyped(evt);
            }
        });

        jLabel15.setText("Mother's Mobile :");

        mothermobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mothermobileKeyTyped(evt);
            }
        });

        jLabel16.setText("Home :");

        homenum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homenumKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Contact Details");

        javax.swing.GroupLayout CDPanalLayout = new javax.swing.GroupLayout(CDPanal);
        CDPanal.setLayout(CDPanalLayout);
        CDPanalLayout.setHorizontalGroup(
            CDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CDPanalLayout.createSequentialGroup()
                .addGroup(CDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CDPanalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mothermobile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CDPanalLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homenum, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CDPanalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CDPanalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(fathermobile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(231, Short.MAX_VALUE)))
        );
        CDPanalLayout.setVerticalGroup(
            CDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CDPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(CDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(homenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(mothermobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(CDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CDPanalLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(CDPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(fathermobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertLayout = new javax.swing.GroupLayout(insert);
        insert.setLayout(insertLayout);
        insertLayout.setHorizontalGroup(
            insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addComponent(RDPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jButton2))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addComponent(PDPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CDPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ParentDPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        insertLayout.setVerticalGroup(
            insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertLayout.createSequentialGroup()
                        .addComponent(PDPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(RDPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(84, 84, 84))))
                    .addGroup(insertLayout.createSequentialGroup()
                        .addComponent(ParentDPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(CDPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 198, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Insert New Record", insert);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed

        String userinp = txt_search.getText();
        int useri = Integer.parseInt(userinp);
        String sql1 = "SELECT AdNo,FullName,NameWithInitial,Birthday,Address,reg_date FROM student_personal_details WHERE AdNo=?";
        try {
            pst = conn.prepareStatement(sql1);
            pst.setInt(1, useri);
            rs = pst.executeQuery();

        } catch (Exception e) {
            System.out.println(e);
        }
        tbl_students.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btn_searchActionPerformed

    private void tbl_studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentsMouseClicked
        txt_siblings.setText("");
        String userinp = txt_search.getText();
        int useri = Integer.parseInt(userinp);
        int rr = tbl_students.getSelectedRow();
        String AdNo = tbl_students.getValueAt(rr, 0).toString();
        String FullName = tbl_students.getValueAt(rr, 1).toString();
        String NameWI = tbl_students.getValueAt(rr, 2).toString();
        String Birthday = tbl_students.getValueAt(rr, 3).toString();
        String Address = tbl_students.getValueAt(rr, 4).toString();
        String regdate1 = tbl_students.getValueAt(rr, 5).toString();
        java.util.Date date;
        java.util.Date reg;
        try {
            date = new SimpleDateFormat("dd/MM/yyyy").parse(Birthday);
            txt_birthday.setDate(date);

            reg = new SimpleDateFormat("dd/MM/yyyy").parse(regdate1);
            txt_regdate.setDate(reg);
        } catch (ParseException ex) {
            Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

        txt_index.setText(AdNo);
        txt_full_name.setText(FullName);
        txt_name_initial.setText(NameWI);
        txt_address.setText(Address);

        //parentdetails
        int ad = Integer.parseInt(AdNo);
        String sql2 = "SELECT std_ad_no,std_mother_name,std_mother_occupation,std_father_name,srd_father_occupation FROM student_parent_details WHERE std_ad_no=?";
        try {
            pst = conn.prepareStatement(sql2);
            pst.setInt(1, ad);
            rs = pst.executeQuery();
            if (rs.next()) {
                String mothername = rs.getString("std_mother_name");
                String motheroc = rs.getString("std_mother_occupation");
                String fathername = rs.getString("std_father_name");
                String father0c = rs.getString("srd_father_occupation");

                //display
                txt_mother_name.setText(mothername);
                txt_mother_occupation.setText(motheroc);
                txt_father_name.setText(fathername);
                txt_father_occupation.setText(father0c);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        //contactDetails
        String sql3 = "Select std_ad_no,std_home,std_father_mobile,std_mother_mobile From student_contact_details where std_ad_no=?";
        try {
            pst = conn.prepareStatement(sql3);
            pst.setInt(1, ad);
            rs = pst.executeQuery();
            if (rs.next()) {
                String home = rs.getString("std_home");
                String father = rs.getString("std_father_mobile");
                String mother = rs.getString("std_mother_mobile");

                txt_father_mobile.setText(father);
                txt_mother_mobile.setText(mother);
                txt_home.setText(home);
            }
        } catch (Exception e) {
            System.out.println(e);

        }

        String sql6 = "SELECT C.class_grade, C.class_subclass, min(S.std_adno) FROM student_class S, classes C WHERE S.std_adno=?";
        try {
            pst = conn.prepareStatement(sql6);
            pst.setInt(1, useri);
            rs = pst.executeQuery();

            if (rs.next()) {
                String grade = rs.getString("C.class_grade");
                String sub = rs.getString("C.class_subclass");

                StringBuilder buffer = new StringBuilder();
                buffer.append(grade).append(" ").append(sub);
                String newclass = buffer.toString();

                Class_reg.setText(newclass);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

        int id = Integer.parseInt(txt_index.getText());
        String searchsib = "SELECT std_ad_no, std_sib_ad FROM student_siblings_details WHERE std_ad_no=?";
        try {
            pst = conn.prepareStatement(searchsib);
            pst.setInt(1, id);
            rs = pst.executeQuery();

            while (rs.next()) {
                int sibID = rs.getInt("std_sib_ad");
                String sibdetails = "SELECT AdNo, FullName FROM student_personal_details WHERE AdNo=?";
                pst = conn.prepareStatement(sibdetails);
                pst.setInt(1, sibID);
                ResultSet rs1;
                rs1 = pst.executeQuery();
                if (rs1.next()) {
                    String name = rs1.getString("FullName");
                    txt_siblings.append(name + "\n");
                    System.out.println(name);
                    continue;
                }

                System.out.println(sibID);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_tbl_studentsMouseClicked

    private void combo_gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_gradeActionPerformed

        combo_subclass.removeAllItems();
        Date date = new Date();
        Calendar calendar = new GregorianCalendar();
        calendar.setTime(date);
        int year = calendar.get(Calendar.YEAR);

        String grade = (String) combo_grade.getSelectedItem();

        String sql1 = "SELECT class_grade,class_subclass,class_year FROM classes WHERE class_year=? AND class_grade=?";
        try {
            pst = conn.prepareStatement(sql1);
            pst.setInt(1, year);
            pst.setString(2, grade);
            rs = pst.executeQuery();

            while (rs.next()) {
                combo_subclass.addItem(rs.getString("class_subclass"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_combo_gradeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("Malinda");
        if (txt_add.equals("")
                || txt_fullname.equals("") || txt_nameInitial.equals("") || txt_datechooser.equals("") || mothername.equals("") || motherocu.equals("") || fathername.equals("") || fatherocu.equals("") || fathermobile.equals("") || mothermobile.equals("") || homenum.equals("") || regdatechooser.equals("")) {

            JOptionPane.showMessageDialog(rootPane, "Please fill all the fields");

        } else {

            int Adno = 0;
            String newdate = null;
            //personal details 
            String fullname = txt_fullname.getText();
            String nwi = txt_nameInitial.getText();
            Date dob = txt_datechooser.getDate();
            String add = txt_add.getText();

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String strDate = sdf.format(dob);

            //parent details
            String Fathername = fathername.getText();
            String Fatherocu = fatherocu.getText();
            String Mothername = mothername.getText();
            String Motherocu = motherocu.getText();

            //contact details
            String mothermob = mothermobile.getText();
            String fathermob = fathermobile.getText();
            String homeno = homenum.getText();

            //reg details
            Date regdate = regdatechooser.getDate();
            newdate = sdf.format(regdate);
            int grade = Integer.parseInt(combo_grade.getSelectedItem().toString());
            String subclass = combo_subclass.getSelectedItem().toString();

            String personaldetails = "INSERT INTO student_personal_details(FullName,NameWithInitial,Birthday,Address,reg_date) VALUES('" + fullname + "','" + nwi + "','" + strDate + "','" + add + "','" + newdate + "')";
            try {
                pst = conn.prepareStatement(personaldetails);
                pst.execute();

                String getadno = "SELECT AdNo,FullName FROM student_personal_details WHERE FullName=?";
                pst = conn.prepareStatement(getadno);
                pst.setString(1, fullname);
                rs = pst.executeQuery();
                if (rs.next()) {

                    Adno = rs.getInt("AdNo");
                    System.out.println(Adno);
                }

                String parentdetails = "INSERT INTO student_parent_details(std_ad_no, std_mother_name, std_mother_occupation, std_father_name, srd_father_occupation) VALUES ('" + Adno + "','" + Mothername + "','" + Motherocu + "','" + Fathername + "','" + Fatherocu + "')";
                pst = conn.prepareStatement(parentdetails);
                pst.execute();

            } catch (SQLException ex) {
                Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

            String contactDetails = "INSERT INTO student_contact_details (std_ad_no,std_home,std_mother_mobile,std_father_mobile) VALUES ('" + Adno + "','" + homeno + "','" + mothermob + "','" + fathermob + "')";
            try {
                pst = conn.prepareStatement(contactDetails);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

            int classid = 0;
            String classSearch = "SELECT class_id,class_grade,class_subclass FROM classes where class_subclass LIKE '" + subclass + "' AND class_grade = '" + grade + "'";
            try {
                pst = conn.prepareStatement(classSearch);
                rs = pst.executeQuery();
                if (rs.next()) {
                    classid = rs.getInt("class_id");

                }

                String classEnter = "INSERT INTO student_class (std_adno,class_id) VALUES ('" + Adno + "','" + classid + "')";
                pst = conn.prepareStatement(classEnter);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

            for (String line : txtarea_sib.getText().split("\\n")) {
                try {
                    siblingadd(line, Adno);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            JOptionPane.showMessageDialog(ParentDPanal, "Data recorded...!!!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    public void siblingadd(String l, int newID) throws SQLException {
        String searchID = "SELECT AdNo,FullName FROM student_personal_details WHERE Fullname=?";
        pst = conn.prepareStatement(searchID);
        pst.setString(1, l);
        rs = pst.executeQuery();
        if (rs.next()) {
            int sibID = rs.getInt("AdNo");
            String entersib = "INSERT INTO student_siblings_details(std_ad_no,std_sib_ad) VALUES ('" + newID + "','" + sibID + "')";
            pst = conn.prepareStatement(entersib);
            pst.execute();
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String index = txt_sib.getText();
        if (index.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Index No");
        } else {
            int adno = Integer.parseInt(index);
            String sql = "SELECT AdNo, FullName FROM student_personal_details WHERE Adno=?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setInt(1, adno);
                rs = pst.executeQuery();

                if (rs.next()) {
                    String name = rs.getString("FullName");
                    txtarea_sib.append(name + "\n");

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Record not found");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fathermobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fathermobileKeyTyped
        try {
            char c = evt.getKeyChar();
            if (Character.isLetter(c)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_fathermobileKeyTyped

    private void homenumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homenumKeyTyped
        try {
            char c = evt.getKeyChar();
            if (Character.isLetter(c)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_homenumKeyTyped

    private void mothermobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mothermobileKeyTyped
        try {
            char c = evt.getKeyChar();
            if (Character.isLetter(c)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mothermobileKeyTyped

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        indexno = Integer.parseInt(txt_index.getText());
        fullname = txt_full_name.getText();
        nwi = txt_name_initial.getText();
        birthday = txt_birthday.getDate();
        address = txt_address.getText();

        mothernamee = txt_mother_name.getText();;
        motherocuu = txt_mother_occupation.getText();;
        fathernamee = txt_father_name.getText();;
        fatherocuu = txt_father_occupation.getText();;

        mothermob = Integer.parseInt(txt_mother_mobile.getText());
        fathermob = Integer.parseInt(txt_father_mobile.getText());
        homeno = Integer.parseInt(txt_home.getText());

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String strDate = sdf.format(birthday);

        try {
            //personal details update
            String personal = "UPDATE student_personal_details SET FullName='" + fullname + "',NameWithInitial='" + nwi + "',Birthday='" + strDate + "',Address='" + address + "' WHERE AdNo='" + indexno + "'";
            pst = conn.prepareStatement(personal);
            pst.execute(personal);

            //parent details update
            String personalupdate = "UPDATE student_parent_details SET std_mother_name='" + mothername + "',std_mother_occupation='" + motherocu + "',std_father_name='" + fathername + "',srd_father_occupation='" + fatherocu + "' WHERE std_ad_no='" + indexno + "'";
            pst = conn.prepareStatement(personalupdate);
            pst.execute(personalupdate);

            //contact details update
            String contactupdate = "UPDATE student_contact_details SET std_home='" + homeno + "',std_mother_mobile='" + mothermob + "',std_father_mobile='" + fathermob + "' WHERE std_ad_no='" + indexno + "'";
            pst = conn.prepareStatement(contactupdate);
            pst.execute(contactupdate);
            //Success Message
            JOptionPane.showMessageDialog(rootPane, "Successfully updated!");

        } catch (SQLException ex) {
            Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_updateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        JFileChooser savefile = new JFileChooser();
        String pathh;
        int result = savefile.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            Path path = savefile.getSelectedFile().toPath();
            pathh = path.toString().trim();

            String filename = pathh;
            PDDocument doc = new PDDocument();
            PDPage page = new PDPage();

            indexno = Integer.parseInt(txt_index.getText());
            fullname = txt_full_name.getText();
            nwi = txt_name_initial.getText();
            birthday = txt_birthday.getDate();
            address = txt_address.getText().toString().trim();

            mothernamee = txt_mother_name.getText();
            motherocuu = txt_mother_occupation.getText();
            fathernamee = txt_father_name.getText();
            fatherocuu = txt_father_occupation.getText();

            mothermob = Integer.parseInt(txt_mother_mobile.getText());
            fathermob = Integer.parseInt(txt_father_mobile.getText());
            homeno = Integer.parseInt(txt_home.getText());

            doc.addPage(page);

            try {
                PDPageContentStream content = new PDPageContentStream(doc, page);

                PDImageXObject pdImage = PDImageXObject.createFromFile("src\\admin\\logo.png", doc);

                content.drawImage(pdImage, 250, 620);

                //header
                content.beginText();
                content.setFont(PDType1Font.HELVETICA, 26);
                content.moveTextPositionByAmount(220, 550);
                content.drawString("Student Profile");
                content.endText();

                //content
                content.beginText();
                content.setFont(PDType1Font.COURIER_BOLD, 16);
                content.moveTextPositionByAmount(80, 500);
                content.drawString("Personal Details");
                content.endText();
                //content
                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 470);
                content.drawString("1. Index No             :     " + indexno);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 450);
                content.drawString("2. Full Name            :     " + fullname);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 430);
                content.drawString("3. Name with initial    :     " + nwi);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 410);
                content.drawString("4. Date of birth        :     " + birthday);
                content.endText();

                
                content.beginText();
                content.setFont(PDType1Font.COURIER_BOLD, 16);
                content.moveTextPositionByAmount(80, 380);
                content.drawString("Parent Details");
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 350);
                content.drawString("5. Mother's name        :     " + mothernamee);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 320);
                content.drawString("6. Mother's Occupation  :     " + motherocuu);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 300);
                content.drawString("7. Fathers's name       :     " + fathernamee);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 280);
                content.drawString("8. Fathers's occupation :     " + fatherocuu);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER_BOLD, 16);
                content.moveTextPositionByAmount(80, 250);
                content.drawString("Contact Details");
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 220);
                content.drawString("9. Fathers's Contact  :     " + fathermob);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 200);
                content.drawString("10. Fathers's Contact  :     " + mothermob);
                content.endText();

                content.beginText();
                content.setFont(PDType1Font.COURIER, 14);
                content.moveTextPositionByAmount(80, 180);
                content.drawString("11. Home Contact       :     " + homeno);
                content.endText();

                content.close();
                doc.save(filename);
                doc.close();
                System.out.println(System.getProperty("user.dir"));

                
            } catch (IOException ex) {
                Logger.getLogger(AdminPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CDPanal;
    private javax.swing.JPanel CDPanal1;
    private javax.swing.JTextField Class_reg;
    private javax.swing.JPanel PDPanal;
    private javax.swing.JPanel PDPanal1;
    private javax.swing.JPanel ParentDPanal;
    private javax.swing.JPanel ParentDPanal1;
    private javax.swing.JPanel RDPanal;
    private javax.swing.JPanel RDPanal1;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_grade;
    private javax.swing.JComboBox<String> combo_subclass;
    private javax.swing.JTextField fathermobile;
    private javax.swing.JTextField fathername;
    private javax.swing.JTextField fatherocu;
    private javax.swing.JTextField homenum;
    private javax.swing.JPanel insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mothermobile;
    private javax.swing.JTextField mothername;
    private javax.swing.JTextField motherocu;
    private com.toedter.calendar.JDateChooser regdatechooser;
    private javax.swing.JTable tbl_students;
    private javax.swing.JTextField txt_add;
    private javax.swing.JTextField txt_address;
    private com.toedter.calendar.JDateChooser txt_birthday;
    private com.toedter.calendar.JDateChooser txt_datechooser;
    private javax.swing.JTextField txt_father_mobile;
    private javax.swing.JTextField txt_father_name;
    private javax.swing.JTextField txt_father_occupation;
    private javax.swing.JTextField txt_full_name;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JTextField txt_home;
    private javax.swing.JTextField txt_index;
    private javax.swing.JTextField txt_mother_mobile;
    private javax.swing.JTextField txt_mother_name;
    private javax.swing.JTextField txt_mother_occupation;
    private javax.swing.JTextField txt_nameInitial;
    private javax.swing.JTextField txt_name_initial;
    private com.toedter.calendar.JDateChooser txt_regdate;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_sib;
    private javax.swing.JTextArea txt_siblings;
    private javax.swing.JTextArea txtarea_sib;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
